### ISSUE TITLE
Forcing keyword arguments in python3 is not compatible with python2

### ISSUE THREAD

**Issue by szabolcsdombi** [nvbn/py-backwards#37]
I run [py-backwards](https://github.com/nvbn/py-backwards) on [ModernGL](https://github.com/cprogrammer1994/ModernGL)

```s
$ py-backwards -i ModernGL -o compiled -t 2.7
```

```
Compilation succeed:
  target: 2.7
  files: 14
  took: 5.31 seconds
  Additional dependencies:
    six
```

I the compiled version still contains lines like this:

```python
class Buffer:
    def read(self, size=(- 1), *, offset=0):
```

However this syntax is invalid in python2 the `*` argument must be removed.

The result should be:

```python
class Buffer:
    def read(self, size=(- 1), offset=0):
```

Sample code using `*` in python3:

```python
>>> def foo(pos, *, forcenamed):
...   print(pos, forcenamed)
... 
>>> foo(pos=10, forcenamed=20)
10 20
>>> foo(10, forcenamed=20)
10 20
>>> foo(10, 20)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: foo() takes exactly 1 positional argument (2 given)
```

Useful link: [Forced naming of parameters in Python](https://stackoverflow.com/questions/2965271/forced-naming-of-parameters-in-python)

**Comment by szabolcsdombi** [comment]
https://github.com/nvbn/py-backwards/issues/16 related

**Comment by mitar** [comment]
I made: https://github.com/nvbn/py-backwards/pull/41
