### ISSUE TITLE
Online demo

### ISSUE THREAD

**Issue by jpadilla** [nvbn/py-backwards#5]
First of all, thank you so much for putting this together, it's awesome! ✨ 

I was curious at the output, so I put together this simple [online demo](https://py-backwards.herokuapp.com/).

Source is at https://github.com/jpadilla/py-backwards-online

Would love your feedback.

**Comment by nvbn** [comment]
Looks nice, I'll add link to the readme ☺️

**Comment by jpadilla** [comment]
@nvbn that'd be awesome, thanks!

**Comment by jpadilla** [comment]
@nvbn thanks! Just as a heads up, I noticed that bot of these fail with a similar error, still haven't verified what might be going on.

https://py-backwards.herokuapp.com/?target=3.5
https://py-backwards.herokuapp.com/?target=3.6

**Comment by nvbn** [comment]
@jpadilla seems like a bug, I created #8 for that.
